### ISSUE TITLE
Error with nbcat

### ISSUE THREAD

**Issue by arnicas** [vinayak-mehta/nbcommands#19]
Hi,  I just installed and got this error trying nbcat:

`Traceback (most recent call last):
  File "/Users/cherny/miniconda3/envs/pandasnlp/bin/nbcat", line 8, in <module>
    sys.exit(cat())
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/nbcommands/_cat.py", line 42, in cat
    click.echo("\n".join(display(merged.cells)))
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/nbcommands/terminal.py", line 15, in display
    cell["execution_count"] if cell["execution_count"] is not None else " "
KeyError: 'execution_count'`

Any ideas?  Python 3.7, nbcommands-0.3.2

**Comment by polyrand** [comment]
I had that very same issue when I tried this library but didn't have a look at it. I think #20 fixes it.

**Comment by vinayak-mehta** [comment]
Thanks for reporting this! It's now fixed, sorry it took so long.

**Comment by wookayin** [comment]
Please release this!

**Comment by vinayak-mehta** [comment]
Sorry I missed releasing it, doing that right now.

**Comment by vinayak-mehta** [comment]
@arnicas @wookayin Please upgrade to v0.4.0 using `pip install --upgrade nbcommands`.
